### ISSUE TITLE
Having a problems with my websocket bittrex bot

### ISSUE THREAD

**Issue by Sile25** [slazarov/python-bittrex-websocket#11]
Hey, thanks for your work, i'm following your Repository and i learnt a lot from it. I'm trying to build my bot but i had a problem, i posted about it on Stackoverflow. Since you are the only source i found on this stuff and i see you are experienced with the websocket, would you give me some help? Thanks in advance and keep up your awesome work! [https://stackoverflow.com/questions/47889244/adding-variables-to-my-websocket-bot](url)

**Comment by slazarov** [comment]
Hey, thanks for the words. From what I am seeing, you want to stream order fills. There is an example in the /example folder showing you how to do this.

My advice is to go through the documentation which might look long but is in fact very straightforward, then check the examples and use them as a starting point. Afterwards, if you have problems, post them here.

Since, this is not in fact an issue and the code you have posted is not from this library I will be closing this issue.

**Comment by Sile25** [comment]
Well i'd like to convert the code and make it based on your library, since it would solve my problem, but i don't know how to convert my piece of code and make it in your library's form, sorry if i was off topic but this issue is driving me crazy lol! Keep up the good work

**Comment by slazarov** [comment]
To stream filled orders you have to use the method [`subscribe_to_trades` ](https://github.com/slazarov/python-bittrex-websocket#methods). 

The library is handling the data stream for you. What you do with the data afterwards is up to you. I will reiterate again, check the examples, specifically [`record_trades.py`](https://github.com/slazarov/python-bittrex-websocket/blob/master/bittrex_websocket/examples/record_trades.py).

I don't mind helping you, but you must be specific about your issue. Read the docs, try the examples and post issues according to the [Guidelines](https://github.com/slazarov/python-bittrex-websocket/wiki/Creating-issues-guideline)
