### ISSUE TITLE
on_orderbook_update call twice

### ISSUE THREAD

**Issue by kylejan** [slazarov/python-bittrex-websocket#7]
when i use subscribe_to_orderbook and subscribe_to_orderbook_update on same tickers at the same time, i will receive two same nounce on_orderbook_update from different thread. i think you can handle it in the module

**Comment by slazarov** [comment]
If you subscribe to the same ticker in the same thread, you will get the same nounce because the source message is the same. Furthermore, subscribe_to_orderbook_update is a prerequisite for subscribe_to_orderbook. You are right, I should handle it in the module but the most appropriate solution is not to allow subscribe_to_orderbook_update when subscribe_to_orderbook is enabled.

Please, explain what behavior you are expecting. From what I understand you want a different nounce?

Finally, please provide a sample code so issues could be replicated.

**Comment by kylejan** [comment]
no, i do not want a different nounce. i just want although i subscribe these two things, i can still receive update from one thread and the other one will be filtered automatically.

the reason why i want to subscribe_to_orderbook_update and subscribe_to_orderbook at the same time is that:

after i read your souce code on processing the updateExchangeState message. Because you use json structure to store the previous orderbook, when you receive a Type 2 update, you have to use a loop to find the correct index of specific quantity and modify it.

however, in my design, i have another data structure to store the orderbook. i do not need to use a loop to find the correct position to modify the quantity. i can use a price as a key in my data structure, and modify the value directly. in this case, the code efficiency will be improved a lot. Therefore, i want to get the first synced orderbook, and use next orderbook_update message to do the orderbook update process by myself

**Comment by slazarov** [comment]
Thanks, I will look into it. I deleted the previous comment because I realized I might have got the wrong idea. Will post back later.

**Comment by kylejan** [comment]
thanks bro! looking forward to your update, keep in touch

**Comment by slazarov** [comment]
Let's see if I am understanding you correctly.
With `subscribe_to_orderbook` you only want to get a synced snapshot, then apply your design logic through `subscribe_to_orderbook_update`. Since you don't need `subscribe_to_orderbook` to maintain the order book, you want to discard it?

If that's your line of thought, then the following can be done:

- call `unsubscribe_to_orderbook()` which will stop the sync, disable `on_orderbook` and leave only `on_orderbook_update`
- create a new public method to expose the raw `queryExchangeState` invoke
- discuss your design logic and implement it if it's more efficient
