### ISSUE TITLE
logging configuration is being overwritten

### ISSUE THREAD

**Issue by meister245** [slazarov/python-bittrex-websocket#8]
Hey,

I'm using your websocket implementation in my project,
I was logging everything to a file and I noticed that after I used your code, it started to display log messages in the terminal.

Your logging configuration is overwriting mine, I fixed the problem by commenting out line 25 in websocket_client.py.

`logging.basicConfig(level=logging.DEBUG)`

I don't know if there is a more elegant fix, I haven't had experience getting into logging at a deeper level.

**Comment by slazarov** [comment]
Working on that issue, will post back for you to retry.

**Comment by slazarov** [comment]
Test it through:
`pip install git+https://github.com/slazarov/python-bittrex-websocket.git@v0.0.5`

**Comment by meister245** [comment]
Hello,
Yes it is fixed :)

The logging from your library goes to the terminal, while all my logging goes to a file.

**Comment by slazarov** [comment]
v0.0.5 has been pushed to pypi and master. Changes that concern you:
* Added custom logger as per [PR #10](https://github.com/slazarov/python-bittrex-websocket/issues/10) and [Issue #8](https://github.com/slazarov/python-bittrex-websocket/issues/8) in order to avoid conflicts with other `basicConfig` setups
  * Added two new methods `enable_log` and `disable_log`. Check [Other Methods](#other-methods).
  * Logging is now disabled on startup. You have to enable it.

Closing this issue for now.
